name: stocksystem
description: "StockSystem by Ahmet Said Yuksek"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_database: ^11.0.3
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1

  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.6
  provider: ^6.1.2
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
     - assets/images/stocksystem_image_add.png

  uses-material-design: true