// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlPLFAzd77BBeaAoM5qe0dzdlsVRcg_08',
    appId: '1:703677654277:android:0f3996a1614f6d8929c36c',
    messagingSenderId: '703677654277',
    projectId: 'asy-stocksys',
    databaseURL: 'https://asy-stocksys-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'asy-stocksys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFzshl7tZAfF90pG9jD2ijUBPlg3rR0FU',
    appId: '1:703677654277:ios:d9a27ae807afa80029c36c',
    messagingSenderId: '703677654277',
    projectId: 'asy-stocksys',
    databaseURL: 'https://asy-stocksys-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'asy-stocksys.appspot.com',
    iosBundleId: 'com.ahmetsaidyuksek.stocksystem',
  );
}
